### ISSUE TITLE
An async trait mock won't compile in 0.10.1 but did in 0.9

### ISSUE THREAD

**Issue by Sushisource** [asomers/mockall#306]
This looks nearly identical to https://github.com/asomers/mockall/issues/298 but I'm using 0.10.1 and still getting the error. My trait and the manual mock:

```rust
pub type Result<T, E = tonic::Status> = std::result::Result<T, E>;

#[cfg_attr(test, mockall::automock)]
#[async_trait::async_trait]
pub trait Poller<PollResult>
where
    PollResult: Send + Sync + 'static,
{
    async fn poll(&self) -> Option<Result<PollResult>>;
    fn notify_shutdown(&self);
    async fn shutdown(self);
    async fn shutdown_box(self: Box<Self>);
}

#[cfg(test)]
mockall::mock! {
    pub ManualPoller<T: Send + Sync + 'static> {}
    impl<T: Send + Sync + 'static> Poller<T> for ManualPoller<T> {
        fn poll<'a, 'b>(&'a self)
          -> impl Future<Output = Option<Result<T>>> + Send + 'b
            where 'a: 'b, Self: 'b;
        fn notify_shutdown(&self);
        fn shutdown<'a>(self)
          -> impl Future<Output = ()> + Send + 'a
            where Self: 'a;
        fn shutdown_box<'a>(self: Box<Self>)
          -> impl Future<Output = ()> + Send + 'a
            where Self: 'a;
    }
}
```
```text
error[E0759]: `self` has an anonymous lifetime `'_` but it needs to satisfy a `'static` lifetime requirement
  --> src/pollers/mod.rs:43:1
   |
43 | / mockall::mock! {
44 | |     pub ManualPoller<T: Send + Sync + 'static> {}
45 | |     impl<T: Send + Sync + 'static> Poller<T> for ManualPoller<T> {
46 | |         fn poll<'a, 'b>(&'a self)
...  |
56 | |     }
57 | | }
   | | ^
   | | |
   | |_this data with an anonymous lifetime `'_`...
   |   ...is captured and required to live as long as `'static` here
```

**Comment by asomers** [comment]
Did this work on 0.9.1 ?

**Comment by Sushisource** [comment]
@asomers Indeed it did

**Comment by asomers** [comment]
The problem is caused by mocking a trait method that returns a non-static structure on a generic struct.  That conflicts with the specific impl code from PR #274 .  You wouldn't have a problem if:
* `poll` were a struct method instead of a trait method,
* `poll`'s return value were always `'static, or
* `ManualPoller` weren't generic.

This is fixable, but it might take some time.

**Comment by asomers** [comment]
@Sushisource could you please test the branch in the linked PR?

**Comment by Sushisource** [comment]
@asomers Yep, that's worked for me. Thanks!

**Comment by asomers** [comment]
Just released 0.10.2 .  Thanks for the bug report!
