### ISSUE TITLE
Sized self breaks automock

### ISSUE THREAD

**Issue by torsteingrindvik** [asomers/mockall#307]
Using 0.10.1, this does not work:

```rust
#[mockall::automock]
pub trait SizedBreaksMock {
    fn new() -> Self
    where
        Self: Sized;
}
```

The use case for this is that the above function may be part of a larger trait,
as a way to make the trait object safe by opting out of making `new()` dispatchable on a dynamic object of the trait:
https://doc.rust-lang.org/reference/items/traits.html#object-safety

**Comment by asomers** [comment]
Did this work in previous versions of Mockall?  What error message do you get when you try?

**Comment by torsteingrindvik** [comment]
I've only tried the latest version.

This is the error dump:

```
error[E0214]: parenthesized type parameters may only be used with a `Fn` trait
 --> a/tests/mocked.rs:9:1
  |
9 | #[mockall::automock]
  | ^^^^^^^^^^^^^^^^^^^^ only `Fn` traits may use parentheses
  |
  = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0107]: missing generics for associated function `Key::new`
    --> a/tests/mocked.rs:9:1
     |
9    | #[mockall::automock]
     | ^^^^^^^^^^^^^^^^^^^^ expected 1 type argument
     |
note: associated function defined here, with 1 type parameter: `T`
    --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/mockall-0.10.1/src/lib.rs:1535:12
     |
1535 |     pub fn new<T: 'static>() -> Self {
     |            ^^^ -
     = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: use angle brackets to add missing type argument
     |
9    | #[mockall::automock]::<T>
     |                     ^^^^^

error[E0308]: mismatched types
 --> a/tests/mocked.rs:9:1
  |
9 | #[mockall::automock]
  | ^^^^^^^^^^^^^^^^^^^^ expected struct `Key`, found fn item
  |
  = note: expected reference `&Key`
             found reference `&fn() -> Key {Key::new::<_>}`
  = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
 --> a/tests/mocked.rs:9:1
  |
9 | #[mockall::automock]
  | ^^^^^^^^^^^^^^^^^^^^ expected struct `Key`, found fn item
  |
  = note: expected struct `Key`
            found fn item `fn() -> Key {Key::new::<_>}`
  = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: use parentheses to call this function
  |
9 | #[mockall::automock]()
  |                     ^^

error: aborting due to 4 previous errors
```

**Comment by asomers** [comment]
Regression introduced by PR #272 .

**Comment by asomers** [comment]
@torsteingrindvik could you please test the branch in PR #309 ?

**Comment by torsteingrindvik** [comment]
> @torsteingrindvik could you please test the branch in PR #309 ?

Yes, using `mockall = { git = "https://github.com/asomers/mockall", branch = "self_sized" }` fixes the code I put in the top post.
Good work 😃

**Comment by asomers** [comment]
Just released 0.10.2 .  Thanks for the bug report!
