### ISSUE TITLE
0.10.0 breaks a mock that was working with 0.9.1

### ISSUE THREAD

**Issue by chris-zen** [asomers/mockall#298]
Hi, just after updating to 0.10.0 I got a failure for the following mock, which was compiling fine before:

```rust
  mockall::mock! {
    TestTransactionReader {}
    impl TransactionsReader for TestTransactionReader {
      fn read_transactions<'a>(&'a mut self) -> Box<dyn Stream<Item = Result<Transaction>> + Unpin + 'a>;
    }
  }
```

The error that I get says:

```
error[E0759]: `self` has an anonymous lifetime `'_` but it needs to satisfy a `'static` lifetime requirement
  --> src/processors/simple.rs:72:3
   |
72 | /   mockall::mock! {
73 | |     TestTransactionReader {}
74 | |     impl TransactionsReader for TestTransactionReader {
75 | |       fn read_transactions<'a>(
...  |
78 | |     }
79 | |   }
   | |   ^
   | |   |
   | |___this data with an anonymous lifetime `'_`...
   |     ...is captured and required to live as long as `'static` here
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Let me know if there is anything else I should report to help you with this ;-)
Great work. Best

**Comment by asomers** [comment]
Try this patch:
```diff
--- a/mockall_derive/src/mock_function.rs
+++ b/mockall_derive/src/mock_function.rs
@@ -619,10 +619,10 @@ impl MockFunction {
         -> impl ToTokens
     {
         let inner_mod_ident = self.inner_mod_ident();
-        if let Some(sa) = self_args {
+        if let Some(PathArguments::AngleBracketed(abga)) = self_args {
             assert!(!self.is_method_generic(),
                 "specific impls with generic methods are TODO");
-            quote!(#inner_mod_ident::Expectation #sa)
+            quote!(#inner_mod_ident::Expectation #abga)
         } else {
             // staticize any lifetimes.  This is necessary for methods that
             // return non-static types, because the Expectation itself must be
```

**Comment by krojew** [comment]
I just got hit with the same error for the following function:

```
fn foo<'a>(
        &'a self,
        a: i16,
        b: u8,
        c: MagicType,
    ) -> Option<(&'a String, i64)>;
```

**Comment by asomers** [comment]
Have you tried that patch, @krojew ?

**Comment by krojew** [comment]
No, I might try it maybe ~12h later.

**Comment by chris-zen** [comment]
Hi @asomers,

Awesome ! the patch seems to fix the problem with my code.

Thank you very much. Looking forward for a new release 😉

**Comment by alexlapa** [comment]
I've also encountered this issue and confirm that the patch works.

Here's my MRE:

```Rust
#[mockall::automock]
pub trait Foo {
    fn bar<'a>(&'a self) -> Box<dyn Debug + 'a>;
}
```

**Comment by asomers** [comment]
Ok, v0.10.1 is out.  Thanks for the good bug reports!
