### ISSUE TITLE
Cannot mock a trait that returns `Option<Self> where Self: Sized`

### ISSUE THREAD

**Issue by Pet3ris** [asomers/mockall#433]
Don't seem to be able to mock the following trait:

```rust
trait Zen {
    fn zen() -> Option<Self> where Self: Sized;
}
mock! {
    pub Z {}
    impl Zen for Z {
        fn zen() -> Option<Self> where Self: Sized;
    }
}
```

In `mockall = "0.11.2"`.

**Detailed error**

```
error[E0282]: type annotations needed
   --> src/commands/run.rs:311:9
    |
311 | /         mock! {
312 | |             pub Z {}
313 | |             impl Zen for Z {
314 | |                 fn zen() -> Option<Self> where Self: Sized;
315 | |             }
316 | |         }
    | |_________^ cannot infer type
```

**Comment by asomers** [comment]
Your exact code works for me.  Please post a complete example.

**Comment by Pet3ris** [comment]
Works in isolation, thank you!

**Comment by Pet3ris** [comment]
Could this have something to do with `tokio-test`?

```
#[cfg(test)]
mod tests {
    use async_trait::async_trait;
    use mockall::*;

    use super::*;

    #[tokio::test]
    async fn test_mockall() {
        trait Zen {
            fn zen() -> Option<Self> where Self: Sized;
        }
        mock! {
            pub Z {}
            impl Zen for Z {
                fn zen() -> Option<Self> where Self: Sized;
            }
        }
    }
}
```

**Comment by Pet3ris** [comment]
This works:

```rust
#[cfg(test)]
mod tests {
    use async_trait::async_trait;
    use mockall::*;

    use super::*;

    trait Zen {
        fn zen() -> Option<Self> where Self: Sized;
    }
    mock! {
        pub Z {}
        impl Zen for Z {
            fn zen() -> Option<Self> where Self: Sized;
        }
    }

    #[tokio::test]
    async fn test_mockall() {
        let mock = MockZ::new();
    }
}
```
